// Central export for all API modules
export * from './client'
export * from './auth'
export * from './tasks'
export * from './messages'
export * from './projects'
export * from './calendar'
export * from './sites'
export * from './complaints'
export * from './factory'
export * from './inventory'
export * from './accounts'
export * from './hr'
export * from './reports'
export * from './notifications'

// Re-export for convenience
export { authApi } from './auth'
export { tasksApi } from './tasks'
export { messagesApi } from './messages'
export { projectsApi } from './projects'
export { calendarApi } from './calendar'
export { sitesApi } from './sites'
export { complaintsApi } from './complaints'
export { factoryApi } from './factory'
export { inventoryApi } from './inventory'
export { accountsApi } from './accounts'
export { hrApi } from './hr'
export { reportsApi } from './reports'
export { notificationsApi } from './notifications'
export { uploadApi } from './upload'

